image: python:3.8

before_script:
  - pip install --upgrade pip && pip install mkdocs mkdocs-material mkdocstrings

pages:
  stage: deploy
  script:
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - master