from typing import List

from automaps.maptype import MapType

SHOW_DEBUG_INFO: bool
LOG_PATH: str
LOG_FORMAT: str
LOG_LEVEL_SERVER: str
PORT_MAP_SERVER: int
PORTS_WORKERS: List[int]
PORT_REGISTRY: int
QGIS_INSTALLATION_PATH: str
DOWNLOADS_RETAIN_TIME: int
LOGO_PATH: str
FAVICON_PATH: str
PROJECT_TITLE: str
PAGE_TITLE: str
MAPTYPE_TEXT: str
MISSING_ATTRIBUTES_TEXT: str
CREATE_MAP_BUTTON_TEXT: str
WAITING_FOR_SERVER_TEXT: str
NO_SERVER_AVAILABLE_TEXT: str
SPINNER_TEXT: str
MAP_READY_TEXT: str
CUSTOM_HTML: str
DOWNLOAD_BUTTON_STYLE: str
FILEPATH_QGIS_PROJECT: str
MAPTYPES_AVAIL: List[MapType]
db: dict
