from typing import List

from automaps.maptype import MapType

SHOW_DEBUG_INFO: bool
PORT: int
QGIS_INSTALLATION_PATH: str
BASEPATH_FILESERVER: str
LOGO_PATH: str
PROJECT_TITLE: str
MAPTYPE_TEXT: str
MISSING_ATTRIBUTES_TEXT: str
WAITING_FOR_SERVER_TEXT: str
SPINNER_TEXT: str
MAP_READY_TEXT: str
CUSTOM_HTML: str
DOWNLOAD_BUTTON_STYLE: str
FILEPATH_QGIS_PROJECT: str
MAPTYPES_AVAIL: List[MapType]
db: dict
