from automaps.generators.fahrgastzahlen import MapGeneratorFahrgastzahlen
from automaps.generators.ueberblick import MapGeneratorUeberblick
from automaps.generators.pendler import MapGeneratorPendler
